apiVersion: v1
kind: Template
labels:
  template: jenkins-clusterroles
metadata:
  annotations:
    description: Cluster roles and bindings for jenkins CI/CD serviceaccount.
    iconClass: icon-jenkins
    tags: jenkins-clusterroles
  name: jenkins-clusterroles
objects:
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: jenkins-cluster-admin
  roleRef:
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: ${NAME_PREFIX}-jenkins
  userNames:
  - system:serviceaccount:${NAME_PREFIX}-jenkins:jenkins
parameters:
- name: NAME_PREFIX
  value: cicd
